name: Build latest
on:
  push:
    branches: main
    paths-ignore:
      - '**.md'
      - 'docs/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Version and Tag
        run: |
          export NEW_VERSION=v1.${{ github.run_number }}
          export PACKAGE=tecolicom/texlive-groff-ja
          (
            echo NEW_VERSION=$NEW_VERSION
            echo PACKAGE=$PACKAGE
          ) >> $GITHUB_ENV
          git tag $NEW_VERSION
          git push --tags

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.PACKAGE }}:${{ env.NEW_VERSION }}
            ${{ env.PACKAGE }}:latest
            ghcr.io/${{ env.PACKAGE }}:${{ env.NEW_VERSION }}
            ghcr.io/${{ env.PACKAGE }}:latest
