name: Build latest
on:
  push:
    branches: main
    paths-ignore:
      - '**.md'
      - 'docs/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Version and Package
        run: |
          sed 's/^ *//' << END >> $GITHUB_ENV
              NEW_VERSION=v1.${{ github.run_number }}
              PACKAGE=tecolicom/texlive-groff-ja
          END

      # Build Docker Image
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.PACKAGE }}:${{ env.NEW_VERSION }}
            ${{ env.PACKAGE }}:latest
            ghcr.io/${{ env.PACKAGE }}:${{ env.NEW_VERSION }}
            ghcr.io/${{ env.PACKAGE }}:latest

      - name: Set Tag
        run: |
          git tag $NEW_VERSION
          git push --tags

